-- ==========================================================
-- E-Commerce SQL Project
-- File: 08_cte.sql
-- Topic: Common Table Expressions (CTEs)
-- ==========================================================

USE ecommerce_db;


-- ==========================================================
-- 1. Products above the average price
-- ==========================================================

WITH average_price AS (
    SELECT AVG(price) AS avg_price
    FROM products
)
SELECT
    p.product_id,
    p.product_name,
    p.price
FROM products p
CROSS JOIN average_price a
WHERE p.price > a.avg_price;


-- ==========================================================
-- 2. Total spending by each customer
-- ==========================================================

WITH customer_spending AS (
    SELECT
        o.customer_id,
        SUM(oi.quantity * oi.price) AS total_spending
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.customer_id
)
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    cs.total_spending
FROM customers c
JOIN customer_spending cs
    ON c.customer_id = cs.customer_id
ORDER BY cs.total_spending DESC;


-- ==========================================================
-- 3. Top customers by total spending
-- ==========================================================

WITH customer_spending AS (
    SELECT
        o.customer_id,
        SUM(oi.quantity * oi.price) AS total_spending
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.customer_id
)
SELECT
    c.first_name,
    c.last_name,
    cs.total_spending
FROM customers c
JOIN customer_spending cs
    ON c.customer_id = cs.customer_id
ORDER BY cs.total_spending DESC
LIMIT 5;


-- ==========================================================
-- 4. Revenue generated by each product
-- ==========================================================

WITH product_revenue AS (
    SELECT
        product_id,
        SUM(quantity * price) AS revenue
    FROM order_items
    GROUP BY product_id
)
SELECT
    p.product_id,
    p.product_name,
    pr.revenue
FROM products p
JOIN product_revenue pr
    ON p.product_id = pr.product_id
ORDER BY pr.revenue DESC;


-- ==========================================================
-- 5. Revenue generated by each category
-- ==========================================================

WITH category_revenue AS (
    SELECT
        p.category_id,
        SUM(oi.quantity * oi.price) AS revenue
    FROM products p
    JOIN order_items oi
        ON p.product_id = oi.product_id
    GROUP BY p.category_id
)
SELECT
    c.category_id,
    c.category_name,
    cr.revenue
FROM categories c
JOIN category_revenue cr
    ON c.category_id = cr.category_id
ORDER BY cr.revenue DESC;


-- ==========================================================
-- 6. Average order value
-- ==========================================================

WITH order_values AS (
    SELECT
        order_id,
        SUM(quantity * price) AS order_value
    FROM order_items
    GROUP BY order_id
)
SELECT
    AVG(order_value) AS average_order_value
FROM order_values;


-- ==========================================================
-- 7. Customers with more than one order
-- ==========================================================

WITH customer_orders AS (
    SELECT
        customer_id,
        COUNT(order_id) AS total_orders
    FROM orders
    GROUP BY customer_id
)
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    co.total_orders
FROM customers c
JOIN customer_orders co
    ON c.customer_id = co.customer_id
WHERE co.total_orders > 1;


-- ==========================================================
-- 8. Products with low stock
-- ==========================================================

WITH low_stock AS (
    SELECT
        product_id,
        product_name,
        stock
    FROM products
    WHERE stock < 20
)
SELECT *
FROM low_stock
ORDER BY stock ASC;


-- ==========================================================
-- 9. Delivered orders and their customers
-- ==========================================================

WITH delivered_orders AS (
    SELECT
        order_id,
        customer_id,
        order_date,
        total_amount
    FROM orders
    WHERE order_status = 'Delivered'
)
SELECT
    c.first_name,
    c.last_name,
    d.order_id,
    d.order_date,
    d.total_amount
FROM delivered_orders d
JOIN customers c
    ON d.customer_id = c.customer_id
ORDER BY d.order_date;


-- ==========================================================
-- 10. Customer spending with average spending
-- ==========================================================

WITH customer_spending AS (
    SELECT
        o.customer_id,
        SUM(oi.quantity * oi.price) AS total_spending
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.customer_id
),
average_spending AS (
    SELECT
        AVG(total_spending) AS avg_spending
    FROM customer_spending
)
SELECT
    c.first_name,
    c.last_name,
    cs.total_spending,
    a.avg_spending
FROM customers c
JOIN customer_spending cs
    ON c.customer_id = cs.customer_id
CROSS JOIN average_spending a
ORDER BY cs.total_spending DESC;